# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:logfile: log/sidekiq.log
:concurrency: 25
:strict: false
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [high_priority, 3]
development:
  :verbose: true
  :concurrency: 5
